Add ScopedRangeIterator
trishume/syntect pull request #347
Opened 2021-08-11 18:37 UTC by icsaszar

Simple change to also expose the `Range` of the scope and not just the string slice in `ScopeRegionIterator`. 
This is super useful for building custom parsing logic on top of syntect without using the highlighter (which also has `HighlightIterator` and `RangedHighlightIterator`).

2021-08-19 02:46 UTC, trishume requested changes
Thanks for the PR! I think this is a pretty reasonable thing to want. You can get this functionality using the existing API by using a mutable variable which you add the `len` of the `str` pieces to as you go along, but it's less convenient.

Given that it's achievable now with some friction though, I'm hesitant to introduce this much code duplication. Instead I think the current `ScopeRegionIterator` could be renamed and made to return a range *instead of* a `str`, and then the `ScopeRegionIterator` could be easily implemented on top of that by just indexing the range into the line, without duplicating the body. When you have the range it's pretty easy to get the `str` if you want it so I don't think the range version needs to yield three things.

I know I'm a bit late reviewing this and you may not feel like implementing the deduplicated version, if so that's fine, I apologize for the inconvenience of the counter variable.

2021-08-23 16:58 UTC, icsaszar commented
> You can get this functionality using the existing API by using a mutable variable which you add the len of the str pieces to as you go along, but it's less convenient.

Yes, I did some googling before I opened the PR and found this [stack overflow](https://stackoverflow.com/questions/38268529/how-to-get-the-byte-offset-between-str) answer, but I didn't like the idea of using pointer arithmetic.

> Given that it's achievable now with some friction though, I'm hesitant to introduce this much code duplication. Instead I think the current ScopeRegionIterator could be renamed and made to return a range instead of a str, and then the ScopeRegionIterator could be easily implemented on top of that by just indexing the range into the line, without duplicating the body. When you have the range it's pretty easy to get the str if you want it so I don't think the range version needs to yield three things.

Here I chose to return a 3 tuple (slice, range, op) be consistent with the `highlight` module. I'm not sure I understand the part with code duplication, I refactored `ScopedRegionIterator`'s `next` to simply call `ScopeRangeIterator`'s `next` and extract the slice and stack operation.

Also to get it right, you'd like me to change `ScopeRangeIterator` to return `(&'a str, std::ops::Range<usize>, &'a ScopeStackOp)` and `ScopedRegionIterator` to use the returned `Range` and get the slice based on that?

> I know I'm a bit late reviewing this and you may not feel like implementing the deduplicated version, if so that's fine, I apologize for the inconvenience of the counter variable.

No problem, I'll happily do the refactoring.

2021-08-24 03:29 UTC, trishume commented
Huh I must have misread and thought that it was duplicated, I agree that it's actually not. Also huh you're right, I had forgotten the highlight module returned a 3-tuple, not sure why it works that way.

I think it's a little bit cleaner to have it just return a `(std::ops::Range<usize>, &'a ScopeStackOp)` and then do the slicing in `ScopedRegionIterator` like you say. But I now agree it's a small enough deal I'm fine to merge as-is if you don't feel like it.

And the solution I meant with the mutable variable is like
```rust
let mut prefix_len = 0;
for (s, op) in ScopeRegionIterator::new(&ops, line) {
  let range = prefix_len..(prefix_len+s.len());
  prefix_len += s.len();
  // ...
}
```

2021-09-06 18:23 UTC, icsaszar commented
Better late then never, I updated `ScopeRangeIterator` to return `(std::ops::Range<usize>, &'a ScopeStackOp)` and updated the documentation to include references between `ScopeRangeIterator` and `ScopeRegionIterator`.

2021-09-13 03:38 UTC, trishume approved these changes
Looks good, thank you!

2021-09-13 03:58 UTC, merged